export const COMMON_LOGOS = {
  MAKULA_LOGO_LIGHT: require("./common/makula-logo-light.png"),
  MAKULA_LOGO_DARK: require("./common/makula-logo-dark.png"),
  LOGIN_BG: require("./common/login-bg.png"),
  COMBINE_SHAPE_BG: require("./common/Combined-Shape.png"),
  IC_WARNING: require("./common/ic-warning.png"),
  IC_SEARCH: require("./common/search.png"),
  IC_LIST: require("./common/list.png"),
  IC_PROCEDURE: require("./common/ic-procedure.png"),
  IC_SPARE_PART: require("./common/spare_part.png"),
  IC_SCHEDULE: require("./common/schedule.png"),
  IC_WORK_ORDER: require("./common/folder.png"),
  IC_WORK_ORDER_GREY: require("./common/ic_WO_grey.png"),
  IC_WORK_ORDER_BLUE: require("./common/ic_WO_blue.png"),
  IC_MY_WORK_ORDER_GREY: require("./common/ic_myWO_grey.png"),
  IC_MY_WORK_ORDER_BLUR: require("./common/ic_myWO_Blue.png"),
  IC_USER:require("./common/ic_user.png"),
  IC_CROSS:require("./common/S.png"),
}