const SCREENS = {
  LANDING: 'LANDING',
  LOGIN: "LOGIN",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  DASHBOARD: 'Dashboard',
  WORK_ORDER_LISTING: "WORK_ORDER_LISTING",
  WORK_ORDER_DETAIL: "WORK_ORDER_DETAIL"
}

// @ts-ignore
export default SCREENS;